export const typeChallengesSolutions = {
  // warm
  "13":
    "https://ghaiklor.github.io/type-challenges-solutions/en/warm-hello-world.html",

  // easy
  "189":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-awaited.html",
  "533":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-concat.html",
  "43":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-exclude.html",
  "14":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-first.html",
  "268": "https://ghaiklor.github.io/type-challenges-solutions/en/easy-if.html",
  "898":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-includes.html",
  "3312":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-parameters.html",
  "4": "https://ghaiklor.github.io/type-challenges-solutions/en/easy-pick.html",
  "3057":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-push.html",
  "7":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-readonly.html",
  "18":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-tuple-length.html",
  "11":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-tuple-to-object.html",
  "3060":
    "https://ghaiklor.github.io/type-challenges-solutions/en/easy-unshift.html",

  // medium
  "529":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-absolute.html",
  "949":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-anyof.html",
  "191":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-append-argument.html",
  "527":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-append-to-object.html",
  "3326":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-bem-style-string.html",
  "110":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-capitalize.html",
  "12":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-chainable-options.html",
  "27958":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-checkrepeatedtuple.html",
  "4499":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-chunk.html",
  "9":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-deep-readonly.html",
  "645":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-diff.html",
  "2070":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-drop-char.html",
  "2693":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-endswith.html",
  "459":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-flatten.html",
  "3196":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-flip-arguments.html",
  "4179":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-flip.html",
  "3376":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-inordertraversal.html",
  "1042":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-isnever.html",
  "1097":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-isunion.html",
  "5310":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-join.html",
  "612":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-kebabcase.html",
  "15":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-last.html",
  "5317":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-lastindexof.html",
  "298":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-length-of-string.html",
  "5821":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-maptypes.html",
  "599":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-merge.html",
  "2257":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-minusone.html",
  "2793":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-mutable.html",
  "4260":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-nomiwase.html",
  "8640":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-number-range.html",
  "2946":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-objectentries.html",
  "3":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-omit.html",
  "2852":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-omitbytype.html",
  "2757":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-partialbykeys.html",
  "1978":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-percentage-parser.html",
  "296":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-permutation.html",
  "2595":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-pickbytype.html",
  "16":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-pop.html",
  "20":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-promise-all.html",
  "28333":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-public-type.html",
  "8":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-readonly-2.html",
  "1367":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-remove-index-signature.html",
  "25170":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-replace-first.html",
  "116":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-replace.html",
  "119":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-replaceall.html",
  "1130":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-replacekeys.html",
  "2759":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-requiredbykeys.html",
  "2":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-return-type.html",
  "3192":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-reverse.html",
  "3062":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-shift.html",
  "2688":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-startswith.html",
  "531":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-string-to-union.html",
  "8987":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-subsequence.html",
  "4803":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-trim-right.html",
  "108":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-trim.html",
  "106":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-trimleft.html",
  "5140":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-trunc.html",
  "3188":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-tuple-to-nested-object.html",
  "10":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-tuple-to-union.html",
  "62":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-type-lookup.html",
  "5360":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-unique.html",
  "5117":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-without.html",
  "4471":
    "https://ghaiklor.github.io/type-challenges-solutions/en/medium-zip.html",

  // hard
  "114":
    "https://ghaiklor.github.io/type-challenges-solutions/en/hard-camelcase.html",
};
